// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/6/17 11:53:52
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/devilfrank/project/mytools/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/plugins/**/*.{js,ts,mjs}","/Users/devilfrank/project/mytools/composables/**/*.{js,ts,mjs}","/Users/devilfrank/project/mytools/utils/**/*.{js,ts,mjs}","/Users/devilfrank/project/mytools/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/devilfrank/project/mytools/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;